import smtplib

# Configuration
port = 465
smtp_server = "poczta.int.pl"
login = "kl7836771@int.pl"  # Your login generated by Mailtrap
password = ""  # Your password generated by Mailtrap

#information
sender_email = "kl7836771@int.pl"
receiver_email = ['+48785569337@text.plusgsm.pl', "kl7836771@int.pl"]

print('1')

# Plain text content
text = "To jest alert ale sam tekst bez edycji, file = smsAlert - kopia.py"

# Send the email
with smtplib.SMTP_SSL(smtp_server, port) as server:
  print(2)
  server.login(login, password)
  print(3)
  server.sendmail(sender_email, receiver_email, text)
  print(4)
  server.sendmail(sender_email, sender_email, text + '\n' + str(receiver_email))
  server.quit()
print('Sent', f'{text}\n{receiver_email}')