import smtplib
from email.mime.text import MIMEText

# Configuration
port = 465
smtp_server = "poczta.int.pl"
login = "kl7836771@int.pl"  # Your login generated by Mailtrap
password = ""  # Your password generated by Mailtrap

#information
sender_email = "kl7836771@int.pl"
receiver_email = ['+48785569337@text.plusgsm.pl', 'kl7836771@gmail.com']
#eceiver_email = ["kl7836771@int.pl", "kl7836771@gmail.com"]
'''sms_gate = 'text.plusgsm.pl' #email to sms gate, for example text.plusgsm.pl
list_of_recievers = ['+48785569337'] #list of phone numbers WITH country code (pl - +48) as string

receiver_email2 = []
for phone in list_of_recievers:
  receiver_email2.append(f'{phone}@{sms_gate}')

receiver_email.append(receiver_email2[0])'''
print('1')

# Plain text content
text = """\
Subject: TEmat - kopia


To jest alert"""

# Create MIMEText object
message = MIMEText(text, "plain")
message["Subject"] = "To jest temat"
message["From"] = sender_email
message["To"] = str(receiver_email)

# Send the email
with smtplib.SMTP_SSL(smtp_server, port) as server:
  print(2)
  server.login(login, password)
  print(3)
  server.sendmail(sender_email, receiver_email, message.as_string())
  print(4)
  server.sendmail(sender_email, sender_email, message.as_string() + str(receiver_email))
  server.quit()
print('Sent', f'{text}\n{receiver_email}')